resources:
- repo: self
  clean: true
queue:
  name: VSEng-MicroBuildVS2017
  demands: Cmd
variables:
  BuildConfiguration: Release
  TeamName: Roslyn

steps:
- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
  displayName: Install Signing Plugin
  inputs:
    signType: $(SignType)
    esrpSigning: true
  condition: and(succeeded(), ne(variables['SignType'], ''))

- script: eng\common\CIBuild.cmd 
            -configuration $(BuildConfiguration)
            /p:PB_PublishBlobFeedKey=$(PB_PublishBlobFeedKey)
            /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
            /p:DotNetSignType=$(SignType)
            /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
            /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
  displayName: Build

- task: MSBuild@1
  displayName: Package Azure Functions
  inputs:
    solution: src\AzureFunctionPackage\AzureFunctionPackage.csproj
    configuration: $(BuildConfiguration)
    msbuildArguments: /t:Restore;Build

- task: PublishTestResults@1
  displayName: Publish Test Results
  inputs:
    testRunner: XUnit
    testResultsFiles: 'artifacts/TestResults/$(BuildConfiguration)/*.xml'
    mergeTestResults: true
    testRunTitle: 'Unit Tests'
  condition: succeededOrFailed()

- task: NuGetPublisher@0
  displayName: Publish NuGet Packages to MyGet
  inputs:
    searchPattern: 'artifacts\packages\$(BuildConfiguration)\NonShipping\*.nupkg'
    connectedServiceName: 'RoslynTools NuGet feed'
    nuGetVersion: 4.0.0.2283
  condition: succeeded()

# Note that insertion scripts currently depend on bin directory being uploaded to drops.
- task: CopyPublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    CopyRoot: '$(Build.SourcesDirectory)'
    Contents: |
     artifacts\bin
     artifacts\log\$(BuildConfiguration)
     artifacts\TestResults\$(BuildConfiguration)
     artifacts\SymStore\$(BuildConfiguration)
     artifacts\packages\$(BuildConfiguration)
    ArtifactName: '$(Build.BuildNumber)'
    ArtifactType: FilePath
    TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)\$(Build.SourceBranchName)'
  condition: succeededOrFailed()

- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: Cleanup
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: Publish MicroBuild Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\MicroBuild\Output'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: FilePath
    TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)\$(Build.SourceBranchName)'
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  displayName: Publish Azure Functions
  inputs:
    connectionType: AzureRM
    azureSubscription: 'Roslyn Infrastructure Azure Resource Management'
    appType: functionApp
    webAppName: roslyn-infra-functions
    Package: 'artifacts/bin/AzureFunctionPackage/$(BuildConfiguration)/AzureFunctionPackage.zip'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'master'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
